title: Mystic Hearth
tagline: "Ground • Gather • Grow"
email: info@mystic-hearth.com
description: >-
  A gathering place for craft, spirit, and story.

url: "https://mystic-hearth.com"   # your live site domain
baseurl: ""                        # leave blank for custom domain

theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - name: Home
    link: /
  - name: Apothecary
    link: /apothecary/
  - name: Enrichment
    link: /enrichment/
  - name: Gallery
    link: /gallery/
